### ISSUE TITLE
Error when passing array to context

### ISSUE THREAD

**Issue by denisprsa** [jasnell/activitystrea.ms#13]
Hey, I found an error when defining custom property in context. I used following code:

```javascript 
AS2.activity()
    .context([
        "https://www.w3.org/ns/activitystreams",
        { vcard: 'http://www.w3.org/2006/vcard/ns#' }
    ])
    .actor(
        AS2.person()
            .name(`${data.user.firstName} ${data.user.lastName}`)
            .id(data.user.id)
    )
    .object(
        AS2.offer()
            .name(data.offer.title)
            .id(data.offer.id)
            .set('vcard:given-name', 'test')
    )
    .name(name)
    .content(content)
    .set({h: 'd'})
    .published(datetime)
    .prettyWrite((err, string) => {
        if (err) {
            return reject(new ServiceError(err.message));
        }
        
        console.log(string)
        resolve(string); 
    }); 
```

Which throws error, that .set() function does not exist. 

```
TypeError: base.set is not a function
    at AsObjectBuilder.set (/home/activity-service/node_modules/activitystrea.ms/src/models/_base.js:413:25)
    at AsObjectBuilder.context (/home/activity-service/node_modules/activitystrea.ms/src/models/_object.js:304:10)
    at buildActivity.buildOfferEvent.Promise (/home/activity-service/src/helpers/build-activity.js:9:1575)
    at BuildActivity.buildOfferEvent (/home/activity-service/src/helpers/build-activity.js:9:1490)
    at Context.done (/home/activity-service/src/helpers/build-activity.spec.js:9:943)
    at callFnAsync (/home/activity-service/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/home/activity-service/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/home/activity-service/node_modules/mocha/lib/runner.js:443:10)
    at /home/activity-service/node_modules/mocha/lib/runner.js:549:12
    at next (/home/activity-service/node_modules/mocha/lib/runner.js:361:14)
    at /home/activity-service/node_modules/mocha/lib/runner.js:371:7
    at next (/home/activity-service/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/home/activity-service/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

I believe there should be BaseBuilder insted of Base object.
```javascript
// let base = new BaseBuilder(); ??
let base = new Base(); 
for (let k of Object.keys(value)) {
      let v = value[k];
      if (k === '@id') base.id(v);
      else if (k === '@type') base.type(v);
      else base.set(k, v);
}
```

**Comment by evanp** [comment]
Thanks! This is good to know.
